### ISSUE TITLE
Allow DRF to work with SessionAuthentication

### ISSUE THREAD

**Issue by brianhelba** [girder/django-s3-file-field#112]
When `REST_FRAMEWORK.DEFAULT_AUTHENTICATION_CLASSES` includes `SessionAuthentication` (which is the default), views are expected have a CSRF token included. The Javascript client does not do this.

**Comment by dchiquit** [comment]
`drf-yasg` uses SessionAuthentication to authenticate, so until this is fixed apps cannot use `drf-yasg` to perform authenticated requests while also using S3FF.

**Comment by brianhelba** [comment]
@dchiquit In `django-composed-configuration` (which I realize is not a requirement for using S3FF), [we don't use `SessionAthentication` , because `OAuth2Authentication` is used instead](https://github.com/girder/django-composed-configuration/blob/b95a8aa817f0b063ef593a9436e9487278af8056/composed_configuration/_rest_framework.py#L29).

However, `BasicAuthentication` is also allowed and [YASG's Swagger is configured to only use Basic Auth](https://github.com/girder/django-composed-configuration/blob/b95a8aa817f0b063ef593a9436e9487278af8056/composed_configuration/_rest_framework.py#L62):

This was done mostly with the intent of minimizing the number of different authentication types which are exposed, while dealing with the fact that YASG doesn't properly support OAuth. However, I wonder whether it effectively resolves this issue for that narrow set of circumstances? In other words, if DRF is globally configured to use `BasicAuthentication` instead of `SessionAthentication`, is there still a problem?

To be clear, I still want to resolve this for *all* S3FF users, and I think #173 may be the best way to do so, but I want to understand the problem better.

**Comment by dchiquit** [comment]
Dandi has `SessionAuthentication` turned on so the normal auth flow works with https://api.dandiarchive.org/swagger/. If we were to turn it off and only support `BasicAuthentication` on the swagger page, my understanding is that developers would have to register Django users so they could authenticate without using the OAuth flow. Dandi specifically has not run into this problem because it doesn't use the JS client. 

`BasicAuthentication` does work for https://app.shapeworks-cloud.org/api/docs/swagger/, which is where I ran into the problem, but it would be nice to support the normal `Django Login` button.

**Comment by dchiquit** [comment]
I just discovered https://docs.djangoproject.com/en/3.1/ref/csrf/#django.views.decorators.csrf.csrf_exempt, perhaps that is the more general solution.
